// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcFozkGj4kgU3Li0Kj0za7qYRN-yNBesc',
    appId: '1:111942703568:web:692d3723bb08b43a76c1d5',
    messagingSenderId: '111942703568',
    projectId: 'chatapp-beecd',
    authDomain: 'chatapp-beecd.firebaseapp.com',
    storageBucket: 'chatapp-beecd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXIAEMQLGhskVWbrn91Am_HA0ZzYSIYjc',
    appId: '1:111942703568:android:e5c02ac38b972c2976c1d5',
    messagingSenderId: '111942703568',
    projectId: 'chatapp-beecd',
    storageBucket: 'chatapp-beecd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXRf1X80QR19I38JCkpG7Y7txgZzbs8QI',
    appId: '1:111942703568:ios:732a3135761c310576c1d5',
    messagingSenderId: '111942703568',
    projectId: 'chatapp-beecd',
    storageBucket: 'chatapp-beecd.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXRf1X80QR19I38JCkpG7Y7txgZzbs8QI',
    appId: '1:111942703568:ios:732a3135761c310576c1d5',
    messagingSenderId: '111942703568',
    projectId: 'chatapp-beecd',
    storageBucket: 'chatapp-beecd.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcFozkGj4kgU3Li0Kj0za7qYRN-yNBesc',
    appId: '1:111942703568:web:c7e710cb1a0e1f3576c1d5',
    messagingSenderId: '111942703568',
    projectId: 'chatapp-beecd',
    authDomain: 'chatapp-beecd.firebaseapp.com',
    storageBucket: 'chatapp-beecd.appspot.com',
  );
}
